package pers.huidong.ddmall.db.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
/**
 * Database Table Remarks:
 *   订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ddmall_order
 */
public class DdmallOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ddmall_order
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ddmall_order
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户表的用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     * Database Column Remarks:
     *   订单状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.order_status
     *
     * @mbg.generated
     */
    private Short orderStatus;

    /**
     * Database Column Remarks:
     *   售后状态，0是可申请，1是用户已申请，2是管理员审核通过，3是管理员退款成功，4是管理员审核拒绝，5是用户已取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.aftersale_status
     *
     * @mbg.generated
     */
    private Short aftersaleStatus;

    /**
     * Database Column Remarks:
     *   收货人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     * Database Column Remarks:
     *   收货人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   收货具体地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   用户订单留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * Database Column Remarks:
     *   商品总费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     * Database Column Remarks:
     *   配送费用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.freight_price
     *
     * @mbg.generated
     */
    private BigDecimal freightPrice;

    /**
     * Database Column Remarks:
     *   优惠券减免
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.coupon_price
     *
     * @mbg.generated
     */
    private BigDecimal couponPrice;

    /**
     * Database Column Remarks:
     *   用户积分减免
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.integral_price
     *
     * @mbg.generated
     */
    private BigDecimal integralPrice;

    /**
     * Database Column Remarks:
     *   团购优惠价减免
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.groupon_price
     *
     * @mbg.generated
     */
    private BigDecimal grouponPrice;

    /**
     * Database Column Remarks:
     *   订单费用， = goods_price + freight_price - coupon_price
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.order_price
     *
     * @mbg.generated
     */
    private BigDecimal orderPrice;

    /**
     * Database Column Remarks:
     *   实付费用， = order_price - integral_price
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.actual_price
     *
     * @mbg.generated
     */
    private BigDecimal actualPrice;

    /**
     * Database Column Remarks:
     *   微信付款编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.pay_id
     *
     * @mbg.generated
     */
    private String payId;

    /**
     * Database Column Remarks:
     *   微信付款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.pay_time
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     * Database Column Remarks:
     *   发货编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.ship_sn
     *
     * @mbg.generated
     */
    private String shipSn;

    /**
     * Database Column Remarks:
     *   发货快递公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.ship_channel
     *
     * @mbg.generated
     */
    private String shipChannel;

    /**
     * Database Column Remarks:
     *   发货开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.ship_time
     *
     * @mbg.generated
     */
    private LocalDateTime shipTime;

    /**
     * Database Column Remarks:
     *   实际退款金额，（有可能退款金额小于实际支付金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.refund_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundAmount;

    /**
     * Database Column Remarks:
     *   退款方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.refund_type
     *
     * @mbg.generated
     */
    private String refundType;

    /**
     * Database Column Remarks:
     *   退款备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.refund_content
     *
     * @mbg.generated
     */
    private String refundContent;

    /**
     * Database Column Remarks:
     *   退款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.refund_time
     *
     * @mbg.generated
     */
    private LocalDateTime refundTime;

    /**
     * Database Column Remarks:
     *   用户确认收货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.confirm_time
     *
     * @mbg.generated
     */
    private LocalDateTime confirmTime;

    /**
     * Database Column Remarks:
     *   待评价订单商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.comments
     *
     * @mbg.generated
     */
    private Short comments;

    /**
     * Database Column Remarks:
     *   订单关闭时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_order.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.id
     *
     * @return the value of ddmall_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.id
     *
     * @param id the value for ddmall_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.user_id
     *
     * @return the value of ddmall_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.user_id
     *
     * @param userId the value for ddmall_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.order_sn
     *
     * @return the value of ddmall_order.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.order_sn
     *
     * @param orderSn the value for ddmall_order.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.order_status
     *
     * @return the value of ddmall_order.order_status
     *
     * @mbg.generated
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.order_status
     *
     * @param orderStatus the value for ddmall_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.aftersale_status
     *
     * @return the value of ddmall_order.aftersale_status
     *
     * @mbg.generated
     */
    public Short getAftersaleStatus() {
        return aftersaleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.aftersale_status
     *
     * @param aftersaleStatus the value for ddmall_order.aftersale_status
     *
     * @mbg.generated
     */
    public void setAftersaleStatus(Short aftersaleStatus) {
        this.aftersaleStatus = aftersaleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.consignee
     *
     * @return the value of ddmall_order.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.consignee
     *
     * @param consignee the value for ddmall_order.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.mobile
     *
     * @return the value of ddmall_order.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.mobile
     *
     * @param mobile the value for ddmall_order.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.address
     *
     * @return the value of ddmall_order.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.address
     *
     * @param address the value for ddmall_order.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.message
     *
     * @return the value of ddmall_order.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.message
     *
     * @param message the value for ddmall_order.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.goods_price
     *
     * @return the value of ddmall_order.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.goods_price
     *
     * @param goodsPrice the value for ddmall_order.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.freight_price
     *
     * @return the value of ddmall_order.freight_price
     *
     * @mbg.generated
     */
    public BigDecimal getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.freight_price
     *
     * @param freightPrice the value for ddmall_order.freight_price
     *
     * @mbg.generated
     */
    public void setFreightPrice(BigDecimal freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.coupon_price
     *
     * @return the value of ddmall_order.coupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.coupon_price
     *
     * @param couponPrice the value for ddmall_order.coupon_price
     *
     * @mbg.generated
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.integral_price
     *
     * @return the value of ddmall_order.integral_price
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralPrice() {
        return integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.integral_price
     *
     * @param integralPrice the value for ddmall_order.integral_price
     *
     * @mbg.generated
     */
    public void setIntegralPrice(BigDecimal integralPrice) {
        this.integralPrice = integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.groupon_price
     *
     * @return the value of ddmall_order.groupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getGrouponPrice() {
        return grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.groupon_price
     *
     * @param grouponPrice the value for ddmall_order.groupon_price
     *
     * @mbg.generated
     */
    public void setGrouponPrice(BigDecimal grouponPrice) {
        this.grouponPrice = grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.order_price
     *
     * @return the value of ddmall_order.order_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.order_price
     *
     * @param orderPrice the value for ddmall_order.order_price
     *
     * @mbg.generated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.actual_price
     *
     * @return the value of ddmall_order.actual_price
     *
     * @mbg.generated
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.actual_price
     *
     * @param actualPrice the value for ddmall_order.actual_price
     *
     * @mbg.generated
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.pay_id
     *
     * @return the value of ddmall_order.pay_id
     *
     * @mbg.generated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.pay_id
     *
     * @param payId the value for ddmall_order.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.pay_time
     *
     * @return the value of ddmall_order.pay_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.pay_time
     *
     * @param payTime the value for ddmall_order.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.ship_sn
     *
     * @return the value of ddmall_order.ship_sn
     *
     * @mbg.generated
     */
    public String getShipSn() {
        return shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.ship_sn
     *
     * @param shipSn the value for ddmall_order.ship_sn
     *
     * @mbg.generated
     */
    public void setShipSn(String shipSn) {
        this.shipSn = shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.ship_channel
     *
     * @return the value of ddmall_order.ship_channel
     *
     * @mbg.generated
     */
    public String getShipChannel() {
        return shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.ship_channel
     *
     * @param shipChannel the value for ddmall_order.ship_channel
     *
     * @mbg.generated
     */
    public void setShipChannel(String shipChannel) {
        this.shipChannel = shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.ship_time
     *
     * @return the value of ddmall_order.ship_time
     *
     * @mbg.generated
     */
    public LocalDateTime getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.ship_time
     *
     * @param shipTime the value for ddmall_order.ship_time
     *
     * @mbg.generated
     */
    public void setShipTime(LocalDateTime shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.refund_amount
     *
     * @return the value of ddmall_order.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.refund_amount
     *
     * @param refundAmount the value for ddmall_order.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.refund_type
     *
     * @return the value of ddmall_order.refund_type
     *
     * @mbg.generated
     */
    public String getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.refund_type
     *
     * @param refundType the value for ddmall_order.refund_type
     *
     * @mbg.generated
     */
    public void setRefundType(String refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.refund_content
     *
     * @return the value of ddmall_order.refund_content
     *
     * @mbg.generated
     */
    public String getRefundContent() {
        return refundContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.refund_content
     *
     * @param refundContent the value for ddmall_order.refund_content
     *
     * @mbg.generated
     */
    public void setRefundContent(String refundContent) {
        this.refundContent = refundContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.refund_time
     *
     * @return the value of ddmall_order.refund_time
     *
     * @mbg.generated
     */
    public LocalDateTime getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.refund_time
     *
     * @param refundTime the value for ddmall_order.refund_time
     *
     * @mbg.generated
     */
    public void setRefundTime(LocalDateTime refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.confirm_time
     *
     * @return the value of ddmall_order.confirm_time
     *
     * @mbg.generated
     */
    public LocalDateTime getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.confirm_time
     *
     * @param confirmTime the value for ddmall_order.confirm_time
     *
     * @mbg.generated
     */
    public void setConfirmTime(LocalDateTime confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.comments
     *
     * @return the value of ddmall_order.comments
     *
     * @mbg.generated
     */
    public Short getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.comments
     *
     * @param comments the value for ddmall_order.comments
     *
     * @mbg.generated
     */
    public void setComments(Short comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.end_time
     *
     * @return the value of ddmall_order.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.end_time
     *
     * @param endTime the value for ddmall_order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.add_time
     *
     * @return the value of ddmall_order.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.add_time
     *
     * @param addTime the value for ddmall_order.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.update_time
     *
     * @return the value of ddmall_order.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.update_time
     *
     * @param updateTime the value for ddmall_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_order
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_order.deleted
     *
     * @return the value of ddmall_order.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_order.deleted
     *
     * @param deleted the value for ddmall_order.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ddmall_order
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ddmall_order
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        orderSn("order_sn", "orderSn", "VARCHAR", false),
        orderStatus("order_status", "orderStatus", "SMALLINT", false),
        aftersaleStatus("aftersale_status", "aftersaleStatus", "SMALLINT", false),
        consignee("consignee", "consignee", "VARCHAR", false),
        mobile("mobile", "mobile", "VARCHAR", false),
        address("address", "address", "VARCHAR", false),
        message("message", "message", "VARCHAR", false),
        goodsPrice("goods_price", "goodsPrice", "DECIMAL", false),
        freightPrice("freight_price", "freightPrice", "DECIMAL", false),
        couponPrice("coupon_price", "couponPrice", "DECIMAL", false),
        integralPrice("integral_price", "integralPrice", "DECIMAL", false),
        grouponPrice("groupon_price", "grouponPrice", "DECIMAL", false),
        orderPrice("order_price", "orderPrice", "DECIMAL", false),
        actualPrice("actual_price", "actualPrice", "DECIMAL", false),
        payId("pay_id", "payId", "VARCHAR", false),
        payTime("pay_time", "payTime", "TIMESTAMP", false),
        shipSn("ship_sn", "shipSn", "VARCHAR", false),
        shipChannel("ship_channel", "shipChannel", "VARCHAR", false),
        shipTime("ship_time", "shipTime", "TIMESTAMP", false),
        refundAmount("refund_amount", "refundAmount", "DECIMAL", false),
        refundType("refund_type", "refundType", "VARCHAR", false),
        refundContent("refund_content", "refundContent", "VARCHAR", false),
        refundTime("refund_time", "refundTime", "TIMESTAMP", false),
        confirmTime("confirm_time", "confirmTime", "TIMESTAMP", false),
        comments("comments", "comments", "SMALLINT", false),
        endTime("end_time", "endTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_order
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}