package pers.huidong.ddmall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * Database Table Remarks:
 *   优惠券信息及规则表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ddmall_coupon
 */
public class DdmallCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   优惠券名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   优惠券介绍，通常是显示优惠券使用限制文字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * Database Column Remarks:
     *   优惠券标签，例如新人专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * Database Column Remarks:
     *   优惠券数量，如果是0，则是无限量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     * Database Column Remarks:
     *   优惠金额，
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.discount
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     * Database Column Remarks:
     *   最少消费金额才能使用优惠券。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.min
     *
     * @mbg.generated
     */
    private BigDecimal min;

    /**
     * Database Column Remarks:
     *   用户领券限制数量，如果是0，则是不限制；默认是1，限领一张.
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.limit
     *
     * @mbg.generated
     */
    private Short limit;

    /**
     * Database Column Remarks:
     *   优惠券赠送类型，如果是0则通用券，用户领取；如果是1，则是注册赠券；如果是2，则是优惠券码兑换；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     * Database Column Remarks:
     *   优惠券状态，如果是0则是正常可用；如果是1则是过期; 如果是2则是下架。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     * Database Column Remarks:
     *   商品限制类型，如果0则全商品，如果是1则是类目限制，如果是2则是商品限制。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.goods_type
     *
     * @mbg.generated
     */
    private Short goodsType;

    /**
     * Database Column Remarks:
     *   商品限制值，goods_type如果是0则空集合，如果是1则是类目集合，如果是2则是商品集合。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.goods_value
     *
     * @mbg.generated
     */
    private Integer[] goodsValue;

    /**
     * Database Column Remarks:
     *   优惠券兑换码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   有效时间限制，如果是0，则基于领取时间的有效天数days；如果是1，则start_time和end_time是优惠券有效期；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.time_type
     *
     * @mbg.generated
     */
    private Short timeType;

    /**
     * Database Column Remarks:
     *   基于领取时间的有效天数days。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.days
     *
     * @mbg.generated
     */
    private Short days;

    /**
     * Database Column Remarks:
     *   使用券开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     * Database Column Remarks:
     *   使用券截至时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddmall_coupon.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.id
     *
     * @return the value of ddmall_coupon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.id
     *
     * @param id the value for ddmall_coupon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.name
     *
     * @return the value of ddmall_coupon.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.name
     *
     * @param name the value for ddmall_coupon.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.desc
     *
     * @return the value of ddmall_coupon.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.desc
     *
     * @param desc the value for ddmall_coupon.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.tag
     *
     * @return the value of ddmall_coupon.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.tag
     *
     * @param tag the value for ddmall_coupon.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.total
     *
     * @return the value of ddmall_coupon.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.total
     *
     * @param total the value for ddmall_coupon.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.discount
     *
     * @return the value of ddmall_coupon.discount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.discount
     *
     * @param discount the value for ddmall_coupon.discount
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.min
     *
     * @return the value of ddmall_coupon.min
     *
     * @mbg.generated
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.min
     *
     * @param min the value for ddmall_coupon.min
     *
     * @mbg.generated
     */
    public void setMin(BigDecimal min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.limit
     *
     * @return the value of ddmall_coupon.limit
     *
     * @mbg.generated
     */
    public Short getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.limit
     *
     * @param limit the value for ddmall_coupon.limit
     *
     * @mbg.generated
     */
    public void setLimit(Short limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.type
     *
     * @return the value of ddmall_coupon.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.type
     *
     * @param type the value for ddmall_coupon.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.status
     *
     * @return the value of ddmall_coupon.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.status
     *
     * @param status the value for ddmall_coupon.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.goods_type
     *
     * @return the value of ddmall_coupon.goods_type
     *
     * @mbg.generated
     */
    public Short getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.goods_type
     *
     * @param goodsType the value for ddmall_coupon.goods_type
     *
     * @mbg.generated
     */
    public void setGoodsType(Short goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.goods_value
     *
     * @return the value of ddmall_coupon.goods_value
     *
     * @mbg.generated
     */
    public Integer[] getGoodsValue() {
        return goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.goods_value
     *
     * @param goodsValue the value for ddmall_coupon.goods_value
     *
     * @mbg.generated
     */
    public void setGoodsValue(Integer[] goodsValue) {
        this.goodsValue = goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.code
     *
     * @return the value of ddmall_coupon.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.code
     *
     * @param code the value for ddmall_coupon.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.time_type
     *
     * @return the value of ddmall_coupon.time_type
     *
     * @mbg.generated
     */
    public Short getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.time_type
     *
     * @param timeType the value for ddmall_coupon.time_type
     *
     * @mbg.generated
     */
    public void setTimeType(Short timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.days
     *
     * @return the value of ddmall_coupon.days
     *
     * @mbg.generated
     */
    public Short getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.days
     *
     * @param days the value for ddmall_coupon.days
     *
     * @mbg.generated
     */
    public void setDays(Short days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.start_time
     *
     * @return the value of ddmall_coupon.start_time
     *
     * @mbg.generated
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.start_time
     *
     * @param startTime the value for ddmall_coupon.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.end_time
     *
     * @return the value of ddmall_coupon.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.end_time
     *
     * @param endTime the value for ddmall_coupon.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.add_time
     *
     * @return the value of ddmall_coupon.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.add_time
     *
     * @param addTime the value for ddmall_coupon.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.update_time
     *
     * @return the value of ddmall_coupon.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.update_time
     *
     * @param updateTime the value for ddmall_coupon.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddmall_coupon.deleted
     *
     * @return the value of ddmall_coupon.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddmall_coupon.deleted
     *
     * @param deleted the value for ddmall_coupon.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        desc("desc", "desc", "VARCHAR", true),
        tag("tag", "tag", "VARCHAR", false),
        total("total", "total", "INTEGER", false),
        discount("discount", "discount", "DECIMAL", false),
        min("min", "min", "DECIMAL", true),
        limit("limit", "limit", "SMALLINT", true),
        type("type", "type", "SMALLINT", true),
        status("status", "status", "SMALLINT", true),
        goodsType("goods_type", "goodsType", "SMALLINT", false),
        goodsValue("goods_value", "goodsValue", "VARCHAR", false),
        code("code", "code", "VARCHAR", false),
        timeType("time_type", "timeType", "SMALLINT", false),
        days("days", "days", "SMALLINT", true),
        startTime("start_time", "startTime", "TIMESTAMP", false),
        endTime("end_time", "endTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddmall_coupon
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}