package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallComment;
import pers.huidong.ddmall.db.domain.DdmallCommentExample;

public interface DdmallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    long countByExample(DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int insert(DdmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int insertSelective(DdmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    DdmallComment selectOneByExample(DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    DdmallComment selectOneByExampleSelective(@Param("example") DdmallCommentExample example, @Param("selective") DdmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    List<DdmallComment> selectByExampleSelective(@Param("example") DdmallCommentExample example, @Param("selective") DdmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    List<DdmallComment> selectByExample(DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    DdmallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    DdmallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    DdmallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallComment record, @Param("example") DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallComment record, @Param("example") DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}