package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallRole;
import pers.huidong.ddmall.db.domain.DdmallRoleExample;

public interface DdmallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    long countByExample(DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int insert(DdmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int insertSelective(DdmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    DdmallRole selectOneByExample(DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    DdmallRole selectOneByExampleSelective(@Param("example") DdmallRoleExample example, @Param("selective") DdmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    List<DdmallRole> selectByExampleSelective(@Param("example") DdmallRoleExample example, @Param("selective") DdmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    List<DdmallRole> selectByExample(DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    DdmallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    DdmallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    DdmallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallRole record, @Param("example") DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallRole record, @Param("example") DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}