package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallKeyword;
import pers.huidong.ddmall.db.domain.DdmallKeywordExample;

public interface DdmallKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    long countByExample(DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int insert(DdmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int insertSelective(DdmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    DdmallKeyword selectOneByExample(DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    DdmallKeyword selectOneByExampleSelective(@Param("example") DdmallKeywordExample example, @Param("selective") DdmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    List<DdmallKeyword> selectByExampleSelective(@Param("example") DdmallKeywordExample example, @Param("selective") DdmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    List<DdmallKeyword> selectByExample(DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    DdmallKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    DdmallKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    DdmallKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallKeyword record, @Param("example") DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallKeyword record, @Param("example") DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}