package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallGoodsSpecification;
import pers.huidong.ddmall.db.domain.DdmallGoodsSpecificationExample;

public interface DdmallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int insert(DdmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(DdmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    DdmallGoodsSpecification selectOneByExample(DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    DdmallGoodsSpecification selectOneByExampleSelective(@Param("example") DdmallGoodsSpecificationExample example, @Param("selective") DdmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    List<DdmallGoodsSpecification> selectByExampleSelective(@Param("example") DdmallGoodsSpecificationExample example, @Param("selective") DdmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    List<DdmallGoodsSpecification> selectByExample(DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    DdmallGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    DdmallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    DdmallGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallGoodsSpecification record, @Param("example") DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallGoodsSpecification record, @Param("example") DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}