package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallCategory;
import pers.huidong.ddmall.db.domain.DdmallCategoryExample;

public interface DdmallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    long countByExample(DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int insert(DdmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int insertSelective(DdmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    DdmallCategory selectOneByExample(DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    DdmallCategory selectOneByExampleSelective(@Param("example") DdmallCategoryExample example, @Param("selective") DdmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    List<DdmallCategory> selectByExampleSelective(@Param("example") DdmallCategoryExample example, @Param("selective") DdmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    List<DdmallCategory> selectByExample(DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    DdmallCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    DdmallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    DdmallCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallCategory record, @Param("example") DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallCategory record, @Param("example") DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}