package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallNotice;
import pers.huidong.ddmall.db.domain.DdmallNoticeExample;

public interface DdmallNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    long countByExample(DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int insert(DdmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int insertSelective(DdmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    DdmallNotice selectOneByExample(DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    DdmallNotice selectOneByExampleSelective(@Param("example") DdmallNoticeExample example, @Param("selective") DdmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    List<DdmallNotice> selectByExampleSelective(@Param("example") DdmallNoticeExample example, @Param("selective") DdmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    List<DdmallNotice> selectByExample(DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    DdmallNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    DdmallNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    DdmallNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallNotice record, @Param("example") DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallNotice record, @Param("example") DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}