package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallGoodsProduct;
import pers.huidong.ddmall.db.domain.DdmallGoodsProductExample;

public interface DdmallGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    long countByExample(DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int insert(DdmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(DdmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    DdmallGoodsProduct selectOneByExample(DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    DdmallGoodsProduct selectOneByExampleSelective(@Param("example") DdmallGoodsProductExample example, @Param("selective") DdmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    List<DdmallGoodsProduct> selectByExampleSelective(@Param("example") DdmallGoodsProductExample example, @Param("selective") DdmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    List<DdmallGoodsProduct> selectByExample(DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    DdmallGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    DdmallGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    DdmallGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallGoodsProduct record, @Param("example") DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallGoodsProduct record, @Param("example") DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}