package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallCollect;
import pers.huidong.ddmall.db.domain.DdmallCollectExample;

public interface DdmallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    long countByExample(DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int insert(DdmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int insertSelective(DdmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    DdmallCollect selectOneByExample(DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    DdmallCollect selectOneByExampleSelective(@Param("example") DdmallCollectExample example, @Param("selective") DdmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    List<DdmallCollect> selectByExampleSelective(@Param("example") DdmallCollectExample example, @Param("selective") DdmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    List<DdmallCollect> selectByExample(DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    DdmallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    DdmallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    DdmallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallCollect record, @Param("example") DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallCollect record, @Param("example") DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}