package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallUser;
import pers.huidong.ddmall.db.domain.DdmallUserExample;

public interface DdmallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    long countByExample(DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int insert(DdmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int insertSelective(DdmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    DdmallUser selectOneByExample(DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    DdmallUser selectOneByExampleSelective(@Param("example") DdmallUserExample example, @Param("selective") DdmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    List<DdmallUser> selectByExampleSelective(@Param("example") DdmallUserExample example, @Param("selective") DdmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    List<DdmallUser> selectByExample(DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    DdmallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    DdmallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    DdmallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallUser record, @Param("example") DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallUser record, @Param("example") DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}