package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallSearchHistory;
import pers.huidong.ddmall.db.domain.DdmallSearchHistoryExample;

public interface DdmallSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    long countByExample(DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int insert(DdmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int insertSelective(DdmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    DdmallSearchHistory selectOneByExample(DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    DdmallSearchHistory selectOneByExampleSelective(@Param("example") DdmallSearchHistoryExample example, @Param("selective") DdmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    List<DdmallSearchHistory> selectByExampleSelective(@Param("example") DdmallSearchHistoryExample example, @Param("selective") DdmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    List<DdmallSearchHistory> selectByExample(DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    DdmallSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    DdmallSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    DdmallSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallSearchHistory record, @Param("example") DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallSearchHistory record, @Param("example") DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}