package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallGoods;
import pers.huidong.ddmall.db.domain.DdmallGoodsExample;

public interface DdmallGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    long countByExample(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int insert(DdmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int insertSelective(DdmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectOneByExample(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectOneByExampleSelective(@Param("example") DdmallGoodsExample example, @Param("selective") DdmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectOneByExampleWithBLOBs(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    List<DdmallGoods> selectByExampleSelective(@Param("example") DdmallGoodsExample example, @Param("selective") DdmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    List<DdmallGoods> selectByExampleWithBLOBs(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    List<DdmallGoods> selectByExample(DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    DdmallGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallGoods record, @Param("example") DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DdmallGoods record, @Param("example") DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallGoods record, @Param("example") DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DdmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}