package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallBrand;
import pers.huidong.ddmall.db.domain.DdmallBrandExample;

public interface DdmallBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    long countByExample(DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int insert(DdmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int insertSelective(DdmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    DdmallBrand selectOneByExample(DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    DdmallBrand selectOneByExampleSelective(@Param("example") DdmallBrandExample example, @Param("selective") DdmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    List<DdmallBrand> selectByExampleSelective(@Param("example") DdmallBrandExample example, @Param("selective") DdmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    List<DdmallBrand> selectByExample(DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    DdmallBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    DdmallBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    DdmallBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallBrand record, @Param("example") DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallBrand record, @Param("example") DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}