package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallSystem;
import pers.huidong.ddmall.db.domain.DdmallSystemExample;

public interface DdmallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    long countByExample(DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int insert(DdmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int insertSelective(DdmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    DdmallSystem selectOneByExample(DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    DdmallSystem selectOneByExampleSelective(@Param("example") DdmallSystemExample example, @Param("selective") DdmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    List<DdmallSystem> selectByExampleSelective(@Param("example") DdmallSystemExample example, @Param("selective") DdmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    List<DdmallSystem> selectByExample(DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    DdmallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    DdmallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    DdmallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallSystem record, @Param("example") DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallSystem record, @Param("example") DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}