package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallGroupon;
import pers.huidong.ddmall.db.domain.DdmallGrouponExample;

public interface DdmallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    long countByExample(DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int insert(DdmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(DdmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    DdmallGroupon selectOneByExample(DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    DdmallGroupon selectOneByExampleSelective(@Param("example") DdmallGrouponExample example, @Param("selective") DdmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    List<DdmallGroupon> selectByExampleSelective(@Param("example") DdmallGrouponExample example, @Param("selective") DdmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    List<DdmallGroupon> selectByExample(DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    DdmallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    DdmallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    DdmallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallGroupon record, @Param("example") DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallGroupon record, @Param("example") DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}