package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallCoupon;
import pers.huidong.ddmall.db.domain.DdmallCouponExample;

public interface DdmallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    long countByExample(DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int insert(DdmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(DdmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    DdmallCoupon selectOneByExample(DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    DdmallCoupon selectOneByExampleSelective(@Param("example") DdmallCouponExample example, @Param("selective") DdmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    List<DdmallCoupon> selectByExampleSelective(@Param("example") DdmallCouponExample example, @Param("selective") DdmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    List<DdmallCoupon> selectByExample(DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    DdmallCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    DdmallCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    DdmallCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallCoupon record, @Param("example") DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallCoupon record, @Param("example") DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}