package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallAdmin;
import pers.huidong.ddmall.db.domain.DdmallAdminExample;

public interface DdmallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    long countByExample(DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int insert(DdmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int insertSelective(DdmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    DdmallAdmin selectOneByExample(DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    DdmallAdmin selectOneByExampleSelective(@Param("example") DdmallAdminExample example, @Param("selective") DdmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    List<DdmallAdmin> selectByExampleSelective(@Param("example") DdmallAdminExample example, @Param("selective") DdmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    List<DdmallAdmin> selectByExample(DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    DdmallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    DdmallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    DdmallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallAdmin record, @Param("example") DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallAdmin record, @Param("example") DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}