package pers.huidong.ddmall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.huidong.ddmall.db.domain.DdmallAftersale;
import pers.huidong.ddmall.db.domain.DdmallAftersaleExample;

public interface DdmallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int insert(DdmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(DdmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    DdmallAftersale selectOneByExample(DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    DdmallAftersale selectOneByExampleSelective(@Param("example") DdmallAftersaleExample example, @Param("selective") DdmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    List<DdmallAftersale> selectByExampleSelective(@Param("example") DdmallAftersaleExample example, @Param("selective") DdmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    List<DdmallAftersale> selectByExample(DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    DdmallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DdmallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    DdmallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    DdmallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DdmallAftersale record, @Param("example") DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DdmallAftersale record, @Param("example") DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DdmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DdmallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DdmallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddmall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}